apiVersion: v1
kind: Service
metadata:
  name: exampleadapter
  namespace: istio-system
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9070
      targetPort: 9070
  selector:
    app: exampleadapter

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleadapter
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleadapter
  template:
    metadata:
      labels:
        app: exampleadapter
    spec:
      containers:
        - image: mixer-adapter:12
          name: exampleadapter-app
          ports:
            - containerPort: 9070
              protocol: TCP